/**
 * Lista completa università italiane (pubbliche e principali private)
 * Fonte: MIUR - Ministero dell'Università e della Ricerca
 * Ordinamento alfabetico
 */
export const ITALIAN_UNIVERSITIES = [
  'Istituto Universitario di Architettura di Venezia (IUAV)',
  'IULM - Libera Università di Lingue e Comunicazione',
  'Libera Università di Bolzano',
  'Politecnico di Bari',
  'Politecnico di Milano',
  'Politecnico di Torino',
  'Scuola IMT Alti Studi Lucca',
  'Scuola Normale Superiore di Pisa',
  'Scuola Superiore Sant\'Anna di Pisa',
  'SISSA - Scuola Internazionale Superiore di Studi Avanzati di Trieste',
  'Università Bocconi',
  'Università Campus Bio-Medico di Roma',
  'Università Cattolica del Sacro Cuore',
  'Università Ca\' Foscari Venezia',
  'Università degli Studi dell\'Aquila',
  'Università degli Studi dell\'Insubria',
  'Università degli Studi della Basilicata',
  'Università degli Studi della Campania "Luigi Vanvitelli"',
  'Università degli Studi della Tuscia',
  'Università degli Studi del Molise',
  'Università degli Studi del Piemonte Orientale',
  'Università degli Studi del Sannio',
  'Università degli Studi di Bari "Aldo Moro"',
  'Università degli Studi di Bergamo',
  'Università degli Studi di Bologna',
  'Università degli Studi di Brescia',
  'Università degli Studi di Cagliari',
  'Università degli Studi di Camerino',
  'Università degli Studi di Cassino e del Lazio Meridionale',
  'Università degli Studi di Catania',
  'Università degli Studi di Catanzaro "Magna Græcia"',
  'Università degli Studi di Enna "Kore"',
  'Università degli Studi di Ferrara',
  'Università degli Studi di Firenze',
  'Università degli Studi di Foggia',
  'Università degli Studi di Genova',
  'Università degli Studi di Macerata',
  'Università degli Studi di Messina',
  'Università degli Studi di Milano',
  'Università degli Studi di Milano-Bicocca',
  'Università degli Studi di Modena e Reggio Emilia',
  'Università degli Studi di Napoli "Federico II"',
  'Università degli Studi di Napoli "L\'Orientale"',
  'Università degli Studi di Napoli "Parthenope"',
  'Università degli Studi di Padova',
  'Università degli Studi di Palermo',
  'Università degli Studi di Parma',
  'Università degli Studi di Pavia',
  'Università degli Studi di Perugia',
  'Università degli Studi di Pisa',
  'Università degli Studi di Roma "La Sapienza"',
  'Università degli Studi di Roma "Tor Vergata"',
  'Università degli Studi di Roma Tre',
  'Università degli Studi di Salerno',
  'Università degli Studi di Sassari',
  'Università degli Studi di Siena',
  'Università degli Studi di Teramo',
  'Università degli Studi di Torino',
  'Università degli Studi di Trento',
  'Università degli Studi di Trieste',
  'Università degli Studi di Udine',
  'Università degli Studi di Urbino "Carlo Bo"',
  'Università degli Studi di Verona',
  'Università degli Studi "Gabriele d\'Annunzio" Chieti-Pescara',
  'Università degli Studi "Guglielmo Marconi" (Telematica)',
  'Università degli Studi Internazionali di Roma - UNINT',
  'Università degli Studi "Mediterranea" di Reggio Calabria',
  'Università degli Studi Niccolò Cusano (Telematica)',
  'Università degli Studi Suor Orsola Benincasa di Napoli',
  'Università della Calabria',
  'Università della Valle d\'Aosta',
  'Università "Giustino Fortunato" (Telematica)',
  'Università LUISS "Guido Carli"',
  'Università "Pegaso" (Telematica)',
  'Università per Stranieri di Perugia',
  'Università per Stranieri di Siena',
  'Università Telematica "e-Campus"',
  'Università Telematica "IUL"',
  'Università Telematica Internazionale "Uninettuno"',
  'Università Telematica "Italian University Line"',
  'Università Telematica "Leonardo da Vinci"',
  'Università Telematica "San Raffaele"',
  'Università Telematica "Unimarconi"',
  'Università Vita-Salute San Raffaele',
  'Altra università non in elenco',
];

// Aree di interesse professionali
export const AREAS_OF_INTEREST = [
  'Artificial Intelligence',
  'Machine Learning',
  'Data Science',
  'Data Engineering',
  'Cybersecurity',
  'Web Development',
  'Mobile Development',
  'Cloud Computing',
  'DevOps',
  'Backend Development',
  'Frontend Development',
  'Full Stack Development',
  'Software Engineering',
  'Database Management',
  'Networking',
  'IoT (Internet of Things)',
  'Blockchain',
  'Game Development',
  'Computer Vision',
  'Natural Language Processing',
  'Robotics',
  'Embedded Systems',
  'Big Data',
  'Business Intelligence',
  'IT Consulting',
];

// Preferenze geografiche italiane
export const ITALIAN_CITIES = [
  'Milano',
  'Roma',
  'Torino',
  'Bologna',
  'Firenze',
  'Napoli',
  'Genova',
  'Venezia',
  'Verona',
  'Padova',
  'Trieste',
  'Bari',
  'Catania',
  'Palermo',
  'Pisa',
  'Trento',
  'Perugia',
  'Ancona',
  'Cagliari',
  'Brescia',
  'Parma',
  'Modena',
  'Bergamo',
  'Estero',
  'Ovunque',
];

// Linguaggi di programmazione comuni
export const PROGRAMMING_LANGUAGES = [
  'Python',
  'Java',
  'JavaScript',
  'TypeScript',
  'C',
  'C++',
  'C#',
  'Go',
  'Rust',
  'PHP',
  'Ruby',
  'Swift',
  'Kotlin',
  'Scala',
  'R',
  'MATLAB',
  'SQL',
  'HTML/CSS',
  'Shell/Bash',
];

// Framework e tools comuni
export const FRAMEWORKS_AND_TOOLS = [
  'React',
  'Angular',
  'Vue.js',
  'Next.js',
  'Node.js',
  'Express',
  'Django',
  'Flask',
  'FastAPI',
  'Spring Boot',
  'ASP.NET',
  'Laravel',
  'Ruby on Rails',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'React Native',
  'Flutter',
  'Electron',
  'Bootstrap',
  'Tailwind CSS',
  'Material-UI',
];

// Database
export const DATABASES = [
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'SQLite',
  'Oracle',
  'Microsoft SQL Server',
  'Cassandra',
  'Elasticsearch',
  'DynamoDB',
  'Firebase',
  'Neo4j',
  'MariaDB',
];

// DevOps e tools
export const DEVOPS_TOOLS = [
  'Git',
  'GitHub',
  'GitLab',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'Jenkins',
  'Travis CI',
  'CircleCI',
  'GitHub Actions',
  'Terraform',
  'Ansible',
  'Nginx',
  'Apache',
  'Linux',
];

// Label per tipo di laurea
export const DEGREE_TYPE_LABELS = {
  bachelor: 'Triennale',
  master: 'Magistrale',
};

// Label per stile di lavoro
export const WORK_STYLE_LABELS = {
  remote: 'Remoto',
  hybrid: 'Ibrido',
  onsite: 'In sede',
};

// Label per tipo di azienda
export const COMPANY_TYPE_LABELS = {
  startup: 'Startup',
  corporate: 'Grande azienda',
  consulting: 'Consulenza',
  sme: 'PMI (Piccola/Media Impresa)',
};

// Label per livello inglese
export const ENGLISH_LEVEL_LABELS = {
  A1: 'A1 - Principiante',
  A2: 'A2 - Elementare',
  B1: 'B1 - Intermedio',
  B2: 'B2 - Intermedio superiore',
  C1: 'C1 - Avanzato',
  C2: 'C2 - Padronanza',
  native: 'Madrelingua',
};

// Label per livello skill
export const SKILL_LEVEL_LABELS = {
  basic: 'Base',
  intermediate: 'Intermedio',
  advanced: 'Avanzato',
};
